services:
  # manager:
  #   container_name: manager
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - 3000:3000
  #     - 5555:5555
  #   depends_on:
  #     - db
  #     - file-service
  #   networks:
  #     - default
  #   restart: always
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - default
    restart: always
  file-service:
    container_name: file-service
    image: file-service
    ports:
      - 9000:9000
    networks:
      - default
    restart: always

# volumes:
#   manager-node_modules:
#   manager-next:
