services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data