services:
  # manager:
  #   container_name: manager
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - 3000:3000
  #     - 5555:5555
  #   depends_on:
  #     - mongo
  #     - file-service
  #   networks:
  #     - default
  #   restart: always
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    networks:
      - default
    restart: always
  file-service:
    container_name: file-service
    image: file-service
    ports:
      - 9000:9000
    volumes:
      - uploads:/app/uploads
    networks:
      - default
    restart: always

volumes:
  uploads:
#   manager-node_modules:
#   manager-next:
