import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils"
import Navigation from "@/components/navigations/nav/nav";
import { QueryClientProvider, QueryClient, Query } from "@tanstack/react-query";

const queryClient = new QueryClient();

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <QueryClientProvider client={queryClient}>
          <Navigation />
          <main style={{ height: 'calc(100vh - 72px)' }}>
            {children}
          </main>
        </QueryClientProvider>
      </body>
    </html>
  );
}
