const TRACER_POINT_WIDTH = 12;
const TRACER_POINT_HOVER_WIDTH = 14;
const TRACER_POINT_HEIGHT = 12;
const TRACER_POINT_HOVER_HEIGHT = 14;
const BUFFER = 10;

export { BUFFER, TRACER_POINT_HEIGHT, TRACER_POINT_HOVER_HEIGHT, TRACER_POINT_HOVER_WIDTH, TRACER_POINT_WIDTH };